version: '3.8'
services:
  app:
    image: daflockinger/simple-backend:latest
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
  db:
    image: postgres:14.1-alpine
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sample_backend
    ports:
      - '5432:5432'
    volumes:
      - ./db-schema:/docker-entrypoint-initdb.d
volumes:
  db-schema:
    driver: local